
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2

sudo: required

addons:
  postgresql: "9.5"
  apt:
    packages:
      - openjdk-8-jre-headless

env:
  matrix:

    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE

matrix:
  include:
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0.0
  - nvm use 14.0.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci dev-master
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//') JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
# - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints || travis_terminate 1;
  - moodle-plugin-ci mustache || travis_terminate 1;
  - moodle-plugin-ci grunt || travis_terminate 1;
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

